POST http://localhost:3000/usuario
Content-Type: application/json

{
  "cargo": "usuario",
  "nome": "Luigi",
  "email": "luigi@teste.com",
  "telefone": "(13)99751-4567",
  "senha": "senha123"
}

###

GET http://localhost:3000/usuarios

###

GET http://localhost:3000/usuario/3

###

PUT http://localhost:3000/usuario/3
Content-Type: application/json

{
  "telefone": "(13)12354-1232"
}

###

DELETE http://localhost:3000/usuario/11
